version: 0.2

phases:
  pre_build:
    commands:
      - echo "started"

  build:
    commands:
      - |
        a=$(date "+%d-%m-%y-%H%M")  
        echo "Setting up SSH..."
        aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:ap-south-1:318988877498:secret:pemkey-k3bJr6 --query SecretString --output text > /tmp/ssh_key.pem
        chmod 400 /tmp/ssh_key.pem
        ls -la /tmp/
        cat /tmp/ssh_key.pem
        ncat --wait 5 --verbose -z 172.31.36.243 22
        ip=$(ip addr)
        echo $ip
      
