version: 0.2

phases:
  build:
    commands:
      - echo "Creating AMI backup..."
      - |
        aws ec2 create-image \
          --instance-id i-027962a43049bf313 \
          --name "baclup-CodeDeploy" \
          --tag-specifications "ResourceType=image,Tags=[{Key=name,Value=CodeDeploy}]"
        # Replace i-027962a43049bf313 with your actual EC2 instance ID

# artifacts:
#   files: '**/*'
