version: 0.2

phases:
  pre_build:
    commands:
      - a=$(date "+%D-%H-%M")
      - di=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=AAR*" | grep InstanceId | awk '{print $2}' | sed 's/[",]//g')
      - echo "$di"
      - aws ec2 create-image --instance-id $di --name b-$a --description testing

  build:
    commands:
      - echo "image created"
      - echo "checking for AMI status; this may take up to 10 minutes"
      - aa=$(aws ec2 describe-images --filters "Name=name,Values=b-$a" | grep "State" | grep "," | awk '{print $2}' | sed 's/[",]//g')
      - echo "$aa"
      - counter="1"
      - while [ $counter -eq 1 ]; do
          aa=$(aws ec2 describe-images --filters "Name=name,Values=b-$a" | grep "State" | grep "," | awk '{print $2}' | sed 's/[",]//g')
          if [ "$aa" == "failed" ]; then
            echo "failed"
            exit
          elif [ "$aa" == "available" ]; then
            counter="0"
          elif [ "$aa" == "pending"  ]; then
            echo "pending trying again"
            sleep 20
          else 
            sleep 10
            echo "nothing trying again"
          fi
        done
      - echo "image is available"
      - id=$(aws ec2 describe-images --filters "Name=name,Values=b-$a" | grep "ImageId" | grep "," | awk '{print $2}' | sed 's/[",]//g')
      - aws ec2 run-instances --image-id $id --instance-type t2.micro --key-name demo --subnet-id subnet-0acad34be64e11c77 --security-group-ids sg-0afdd16d5a084eb2a --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=Prod-$a}]"
