version: 0.2

phases:
  pre_build:
    commands:
      - echo "started"

  build:
    commands:
      - |
        ls -la
        pwd
        ip addr
        ssh -i /codebuild/output/src2526760223/src'echo "hi"' 

