version: 0.2

phases:
  pre_build:
    commands:
      - echo "started"

  build:
    commands:
      - |
        ls -la
        pwd
        ip addr
        ssh -i key.pem ec2-user@172.31.36.243 'echo "hi"'


