version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Setting up SSH..."
      # Use the SSH key from the Secrets Manager
      - aws secretsmanager get-secret-value --secret-id <your-secret-arn> --query SecretString --output text > /tmp/ssh_key.pem
      - chmod 400 /tmp/ssh_key.pem
  build:
    commands:
      - echo "Executing SSH commands..."
      # Replace <username> and <hostname> with the appropriate values
      - ssh -i /tmp/ssh_key.pem <username>@<hostname> "ls -l /path/to/remote/directory"
